### ISSUE TITLE
统一的编码格式

### ISSUE THREAD

**Issue by jackfiled** [FA555/ProgrammingHomework#47]
@FA555 
我注意到我们的代码仓库中有着UTF-8与GBK两种编码格式存在，杜佬有没有什么好办法可以统一一下吗？
如果不统一的话，可能会存在部分同学代码中的中文注释会乱码。

**Comment by FA555** [comment]
注意到了，但是不太有想法改

好像常用的 IDE 和 editor 里有且仅有 devc++ 是 GBK 的，不管怎么改都得有人难受，麻

**Comment by jackfiled** [comment]
我大概想的是用Action之类的自动化脚本在每次合并之后自动转一下
但是我不会（

**Comment by FA555** [comment]
主要是，直接 pull 下去看的同学就会被背刺一把（

维持原状好歹不会打破体系（

**Comment by FA555** [comment]
道理上肯定是要统一成 utf8 的，但是实在太多人用 devc++ 了，那些同学全都会懵逼

**Comment by jackfiled** [comment]
艹有点道理
人麻了
